package diabete.configurazione;

/**
 *
 * @author Gabriele Ara
 */
public enum TipoParametro {
    PERCORSO_CSS,
    NOME_FONT,
    COLORE_INTESTAZIONE,
    COLORE_PANNELLO_UTENTI,
    COLORE_UTENTE_SELEZIONATO,
    COLORE_LINEA_GRAFICO,
    COLORE_SFONDO_GRAFICO,
    IP_SERVER,
    IP_LOCALE,
    PORTA_SERVER,
    SOGLIA_GLICEMIA_BASSA,
    SOGLIA_GLICEMIA_ALTA
}
